package fr.ecp.sio.appenginedemo.api;

/**
 * Created by snenon on 13/12/15.
 */


import com.google.appengine.api.blobstore.BlobKey;
import com.google.appengine.api.blobstore.BlobstoreService;
import com.google.appengine.api.blobstore.BlobstoreServiceFactory;
import com.google.appengine.api.images.ImagesService;
import com.google.appengine.api.images.ImagesServiceFactory;
import com.google.appengine.api.images.ServingUrlOptions;
import fr.ecp.sio.appenginedemo.data.UsersRepository;
import fr.ecp.sio.appenginedemo.model.User;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import java.io.IOException;
import java.util.List;
import java.util.Map;


/**
 * This applet manages the avatars (profile pictures): creation, edition
 */
public class ImageServlet extends JsonServlet {


    /**
     * This method returns an upload URL to post the picture
     *
     * @param req a request
     * @return image url
     * @throws ServletException
     * @throws IOException
     * @throws ApiException
     */
    @Override
    protected String doGet(HttpServletRequest req) throws ServletException, IOException, ApiException {
        BlobstoreService blobstoreService = BlobstoreServiceFactory.getBlobstoreService();
        return blobstoreService.createUploadUrl("/image");
    }

    /**
     * This method gets the picture sent to the servlet via the URL generated by doGet,
     * stores it in the blobstore and updates the user
     * @param req the request
     * @return the picture URL
     * @throws ServletException, IOException, ApiException
     */
    @Override
    protected String doPost(HttpServletRequest req) throws ServletException, IOException, ApiException {
        // Initializes the Blobstore and Image services
        BlobstoreService blobstoreService = BlobstoreServiceFactory.getBlobstoreService();

        ImagesService imagesService = ImagesServiceFactory.getImagesService();

        // Authentification
        User currentUser = getAuthenticatedUser(req);
        if (currentUser == null) throw new ApiException(500, "accessDenied", "authorization required");



        // get uploaded picture
        // It would be a good idea to resize and convert the picture
        Map<String, List<BlobKey>> blobs = blobstoreService.getUploads(req);
        List<BlobKey> blobKeys = blobs.get("uploadedFile");
        String uploadedFileKey = blobKeys.get(0).getKeyString();

        // get the serving url of the picture
        String urlImage = imagesService.getServingUrl(ServingUrlOptions.Builder.withBlobKey(blobKeys.get(0)));

        // update user
        UsersRepository.updateAvatar(currentUser, uploadedFileKey, urlImage);

        // return picture url
        return urlImage;
    }
}